#!/usr/bin/env bash

#
# Bootstrapping
#

# fresh: bundler for dotfiles
fresh freshshell/fresh bin/fresh --bin

#
# Shell
#

# dircolors: colorized ls
fresh seebi/dircolors-solarized dircolors.ansi-dark --file=~/.dircolorsrc

# fish: the friendly interactive shell, for humans
fresh-options --file=~/.config/fish/config.fish --marker
    fresh config/fish/config.fish
    fresh config/fish/aliases.fish
    fresh config/fish/colors.fish
fresh-options
for function in ~/.dotfiles/config/fish/functions/*.fish; do
    fresh config/fish/functions/"$(basename "$function")" --file=~/.config/fish/functions/"$(basename "$function")"
done

# fisherman: package manager for fish
fresh config/fish/fishfile --file=~/.config/fish/fishfile
fresh fisherman/fisherman fisher.fish --file=~/.config/fish/functions/fisher.fish

# fzf: universal fuzzy finder
fresh scripts/fzfurl --bin

#
# Editing
#

# neovim: vim improved
fresh scripts/vimprofile --bin
for config in ~/.dotfiles/config/neovim/*.vim; do
    fresh config/neovim/"$(basename "$config")" --file=~/.config/nvim/"$(basename "$config")"
done
fresh k-takata/minpac . --file=~/.config/nvim/pack/minpac/opt/minpac/

# nyaovim: electron gui for neovim
fresh config/nyaovimrc.html --file=~/.config/nyaovim/nyaovimrc.html

#
# Compilers
#

# clang: llvm c front-end
fresh scripts/clang-flags-native --bin

# gcc: gnu compiler collection
fresh scripts/gcc-flags-native --bin

#
# Graphical
#

# alacritty: a fast terminal emulator
fresh config/alacritty.yml --file=~/.config/alacritty/alacritty.yml

# compton: x compositor
fresh config/compton.conf --file=~/.config/compton.conf
fresh scripts/compton-toggle --bin

# dwm: dynamic window manager
fresh scripts/dwmstatus --bin

# dunst: simple notification daemon
fresh config/dunstrc --file=~/.config/dunst/dunstrc

# dmenu: simple 'graphical' menu
fresh scripts/dmenu_run.pl --bin

# evrouter: input event daemon
fresh config/evrouterrc --file=~/.evrouterrc

# gtk: widget toolkit
fresh config/gtk/settings.ini --file=~/.config/gtk-3.0/settings.ini
fresh config/gtk/gtkrc-2.0 --file

# i3: tiling/tabbed window manger
fresh config/i3/config --file=~/.config/i3/config

# redshift: screen tinter
fresh config/redshift.conf --file=~/.config/redshift.conf

# slock: simple screen locker
fresh scripts/xlock --bin

# xbindkeys: global keyboard bindings
fresh config/xbindkeysrc --file

# xmodmap: x keysym configuration
fresh config/Xmodmap --file

# xrdb: x resources database
fresh config/Xresources --file

# x: the x display server
fresh config/xinitrc --file
fresh config/xsession --file
fresh config/xserverrc --file

#
# Audio
#

# alsa: advanced linux sound architecture
fresh config/asoundrc --file=~/.asoundrc

# mpd: music player daemon
fresh config/mpd.conf --file=~/.mpd/mpd.conf

# ncmpcpp: mpd client
fresh config/ncmpcpp/config --file=~/.ncmpcpp/config
fresh config/ncmpcpp/bindings --file=~/.ncmpcpp/bindings

#
# Utilities
#

# 24bit: check a terminal for true color support
fresh scripts/24bit --bin

# aur: the arch user repository
fresh scripts/aurdiff --bin
fresh scripts/aurget --bin

# git: the stupid content tracker
fresh-options --file=~/.config/git/config --marker
    fresh config/git/config
    fresh config/git/aliases
    fresh config/git/colors
fresh-options
fresh config/git/attributes --file=~/.config/git/attributes
fresh config/git/ignore --file=~/.config/git/ignore
fresh config/git/template --file=~/.config/git/template/

# gibo: gitignore boilerplates
fresh simonwhitaker/gitignore-boilerplates gibo --bin

# gnupg: the gnu privacy guard
fresh scripts/pinentry --bin
fresh config/gnupg/gpg.conf --file=~/.gnupg/gpg.conf
fresh config/gnupg/gpg-agent.conf --filter="sed s#HOME#$HOME#" --file=~/.gnupg/gpg-agent.conf
fresh config/gnupg/dirmngr.conf --file=~/.gnupg/dirmngr.conf
fresh config/gnupg/sks-keyservers.netCA.pem --file=~/.gnupg/sks-keyservers.netCA.pem

# htop: interactive process monitor
fresh config/htoprc --file=~/.config/htop/htoprc

# makepkg: arch linux packager
fresh config/makepkg.conf --file=~/.makepkg.conf

# pyenv: python version manager
fresh scripts/pyenv-install --bin

# rbenv: ruby version manager
fresh scripts/rbenv-install --bin
fresh config/rbenv/default-gems --file=~/.rbenv/default-gems

# tmux: terminal multiplexer
fresh-options --file=~/.tmux.conf --marker
    fresh config/tmux/main.conf
    fresh config/tmux/statusline.conf
    if [[ "$(uname)" == "Darwin" ]]; then
        fresh config/tmux/osx.conf
    elif [[ "$(uname)" == "Linux" ]]; then
        fresh config/tmux/linux.conf
    fi
fresh-options
fresh junegunn/dotfiles bin/tmuxwords.rb --bin

fresh_after_build () {
    chmod +w ~/.fresh/build/config-fish-fishfile
    chmod +x ~/.fresh/build/xsession
}

# vi:ft=sh:
