[nord]
    nord0  = "#2e3440"
    nord1  = "#3b4252"
    nord2  = "#434c5e"
    nord3  = "#4c566a"
    nord4  = "#d8dee9"
    nord5  = "#e5e9f0"
    nord6  = "#eceff4"
    nord7  = "#8fbcbb"
    nord8  = "#88c0d0"
    nord9  = "#81a1c1"
    nord10 = "#5e81ac"
    nord11 = "#bf616a"
    nord12 = "#d08770"
    nord13 = "#ebcb8b"
    nord14 = "#a3be8c"
    nord15 = "#b48ead"

    nord1dim  = "#373e4d"
    nord5dim  = "#aeb3bb"
    nord8dim  = "#6d96a5"
    nord9dim  = "#68809a"
    nord11dim = "#94545d"
    nord13dim = "#b29e75"
    nord14dim = "#809575"
    nord15dim = "#8c738c"

[node]
    current  = 19

[node.lts]
    fermium  = 14
    gallium  = 16
    hydrogen = 18
    active   = 18

[python]
    supported = ["3.7", "3.8", "3.9", "3.10", "3.11"]

[packages.macos]
    taps = [
        "homebrew/autoupdate",
        "homebrew/bundle",
        "homebrew/cask",
        "homebrew/cask-fonts",
        "homebrew/cask-versions",
        "homebrew/command-not-found",
        "homebrew/core",
        "homebrew/services",
        "beeftornado/rmtree",
        "microsoft/git",
        "tavianator/tap",
    ]

    formulae = [
        # Toolchain
        "ccache",
        "cmake",
        "pkg-config",

        # Libraries
        "gdbm",
        "gettext",
        "gmp",
        "openssl@1.1",
        "readline",

        # User Programs
        "age",
        "asciinema",
        "bat",
        "bfs",
        "broot",
        "caddy",
        "chezmoi",
        "croc",
        "ctags",
        "curl",
        "curlie",
        "direnv",
        "diskus",
        "dust",
        "duti",
        "eza",
        "fd",
        "fileicon",
        "fish",
        "fzf",
        "gdb",
        "gh",
        "git",
        "git-delta",
        "git-filter-repo",
        "git-interactive-rebase-tool",
        "git-lfs",
        "gnu-getopt",
        "hexyl",
        "htop",
        "hyperfine",
        "jless",
        "jq",
        "less",
        "lftp",
        "mas",
        "mkcert",
        "mosh",
        "mycli",
        "neovim",
        "openssh",
        "pam-reattach",
        "pgcli",
        "pipx",
        "pre-commit",
        "rclone",
        "ripgrep",
        "sd",
        "shellcheck",
        "shfmt",
        "smug",
        "socat",
        "starship",
        "subversion",
        "tealdeer",
        "terminal-notifier",
        "tmate",
        "tmux",
        "tmux-mem-cpu-load",
        "tokei",
        "trash",
        "vivid",
        "watch",
        "watchexec",
        "yq",
        "yubikey-agent",
        "zoxide",
    ]

    casks = [
        "1password",
        "1password-cli",
        "alacritty",
        "appcleaner",
        "bartender",
        "bettertouchtool",
        "contexts",
        "daisydisk",
        "dash",
        "font-source-code-pro",
        "git-credential-manager-core",
        "hex-fiend",
        "hot",
        "iterm2",
        "keka",
        "kekaexternalhelper",
        "maccy",
        "multipass",
        "qmk-toolbox",
        "rectangle-pro",
        "serial",
        "silicon",
        "soundsource",
        "sublime-merge",
        "sublime-text",
        "tailscale",
        "utm",
        "visual-studio-code",
        "vivid",
    ]

    app_store = [
        { name = "Battery Indicator", id = 1206020918 },
        { name = "Boop", id = 1518425043 },
        { name = "ColorSlurp", id = 1287239339 },
        { name = "Dato", id = 1470584107 },
        { name = "Lungo", id = 1263070803 },
        { name = "PCalc", id = 403504866 },
        { name = "Velja", id = 1607635845 },
    ]

[packages.freebsd]
    ports = [
        # Toolchain
        "devel/ccache",
        "devel/cmake",
        "devel/gmake",
        # Libraries
        "databases/gdbm",
        "sqlite3", # origin: databases/sqlite3
        "devel/libffi",
        "devel/ncurses",
        "devel/readline",
        # User Programs
        "archivers/unzip",
        "archivers/zip",
        "benchmarks/hyperfine",
        "databases/py-mycli",
        "databases/py-pgcli",
        "devel/gdb",
        "devel/gh",
        "git", # origin: devel/git
        "devel/git-delta",
        "devel/git-filter-repo",
        "devel/git-lfs",
        "devel/hs-ShellCheck",
        "devel/interactive_rebase_tool",
        "devel/p5-File-MimeInfo",
        "devel/py-pipx",
        "devel/py-pre-commit",
        "devel/shfmt",
        "devel/tig",
        "devel/tokei",
        "devel/universal-ctags",
        "editors/neovim",
        "ftp/curl",
        "ftp/curlie",
        "ftp/lftp",
        "lang/python",
        "lang/python3",
        "misc/broot",
        "misc/getopt",
        "misc/gnu-watch",
        "net/croc",
        "net/mosh",
        "net/rclone",
        "net/socat",
        "net/whois",
        "ports-mgmt/pkg",
        "ports-mgmt/pkg-provides",
        "ports-mgmt/portlint",
        "ports-mgmt/poudriere",
        "security/1password-client",
        "security/age",
        "security/tailscale",
        "shells/bash",
        "shells/fish",
        "shells/starship",
        "sysutils/bfs",
        "sysutils/chezmoi",
        "sysutils/direnv",
        "sysutils/diskus",
        "sysutils/dust",
        "sysutils/eza",
        "sysutils/fd",
        "sysutils/hexyl",
        "sysutils/htop",
        "sysutils/py-qmk",
        "sysutils/smug",
        "sysutils/tealdeer",
        "sysutils/tmate",
        "sysutils/tmux",
        "sysutils/tmux-mem-cpu-load",
        "sysutils/vivid",
        "sysutils/zoxide",
        "textproc/bat",
        "textproc/fzf",
        "textproc/go-yq",
        "textproc/jless",
        "textproc/jq",
        "textproc/py-asciinema",
        "textproc/ripgrep",
        "textproc/sd",
        "www/caddy",
        # missing: mkcert
        # missing: watchexec
    ]

[packages.arch]
    packages = [
        # Toolchain
        "base-devel",
        "ccache",
        "clang",
        "cmake",
        "musl",
        # Libraries
        "bzip2",
        "gdbm",
        "gmp",
        "libffi",
        "libyaml",
        "ncurses",
        "openssl",
        "readline",
        "sqlite",
        "xz",
        "zlib",
        # User Programs
        "1password-cli",
        "age",
        "asciinema",
        "aurpublish",
        "bat",
        "bcc-tools",
        "bfs",
        "broot",
        "caddy",
        "chezmoi",
        "croc",
        "ctags",
        "curlie",
        "direnv",
        "diskus",
        "dool",
        "dust",
        "eza",
        "fd",
        "fish",
        "fuse2",
        "fzf",
        "gdb",
        "git",
        "git-credential-manager-core-bin",
        "git-delta",
        "git-filter-repo",
        "git-interactive-rebase-tool-bin",
        "git-lfs",
        "github-cli",
        "go-yq",
        "handlr-regex",
        "hexyl",
        "htop",
        "hyperfine",
        "jless",
        "jq",
        "lftp",
        "lostfiles",
        "lsof",
        "ltrace",
        "man-db",
        "man-pages",
        "mkcert",
        "mosh",
        "mycli",
        "namcap",
        "neovim",
        "net-tools",
        "pacman-contrib",
        "paru-bin",
        "perf",
        "perl-file-mimeinfo",
        "pgcli",
        "python-pipx",
        "python-pre-commit",
        "qmk",
        "rclone",
        "ripgrep",
        "rr-bin",
        "sd",
        "shellcheck",
        "shfmt",
        "smug",
        "socat",
        "starship",
        "strace",
        "tailscale",
        "tealdeer",
        "tig",
        "tmate",
        "tmux",
        "tmux-mem-cpu-load",
        "tokei",
        "unzip",
        "vivid",
        "watchexec",
        "whois",
        "xdg-utils-handlr",
        "zip",
        "zoxide",
    ]

[wsl.aliases]
    adb        = "adb.exe"
    clion      = "cmd.exe /c clion.cmd"
    cmd        = "cmd.exe"
    goland     = "cmd.exe /c goland.cmd"
    idea       = "cmd.exe /c idea.cmd"
    multipass  = "multipass.exe"
    neovide    = "neovide.exe --wsl"
    powershell = "powershell.exe"
    pycharm    = "cmd /c pycharm.cmd"
    rider      = "cmd /c Rider.cmd"
    smerge     = "smerge.exe"
    studio     = "cmd /c studio.cmd"
    subl       = "subl.exe"
    winget     = "winget.exe"
    wsl        = "wsl.exe"
    ykman      = "ykman.exe"
