[wsl.aliases]
    adb        = "adb.exe"
    clion      = "cmd.exe /c clion.cmd"
    cmd        = "cmd.exe"
    goland     = "cmd.exe /c goland.cmd"
    idea       = "cmd.exe /c idea.cmd"
    multipass  = "multipass.exe"
    neovide    = "neovide.exe --wsl"
    powershell = "powershell.exe"
    pycharm    = "cmd /c pycharm.cmd"
    rider      = "cmd /c Rider.cmd"
    smerge     = "smerge.exe"
    studio     = "cmd /c studio.cmd"
    subl       = "subl.exe"
    winget     = "winget.exe"
    wsl        = "wsl.exe"
    ykman      = "ykman.exe"
