[wsl.aliases]
    adb        = "adb.exe"
    cmd        = "cmd.exe"
    neovide    = "neovide.exe --wsl"
    powershell = "powershell.exe"
    smerge     = "smerge.exe"
    subl       = "subl.exe"
    winget     = "winget.exe"
    wsl        = "wsl.exe"
