# show hidden files and git status
default_flags = "gh"
# show a triangle indicator on the current line
show_selection_mark = true
# use 24bit color always
true_colors = true
# quit with esc at the top level
quit_on_last_cancel = true

[[verbs]]
invocation = 'tailf'
execution = 'tail -f {file}'

[[verbs]]
invocation = 'open'
key = 'enter'
execution = '$EDITOR +{line} {file}'
leave_broot = false

[[verbs]]
invocation = 'edit {subpath}'
shortcut = 'e'
execution = '$EDITOR {directory}/{subpath}'
leave_broot = false

[[verbs]]
invocation = 'git_diff'
shortcut = 'gd'
leave_broot = false
execution = 'git difftool -y {file}'

[[verbs]]
invocation = 'terminal'
key = 'ctrl-t'
execution = '$SHELL'
set_working_dir = true
leave_broot = false
