# Configuration

[settings]
# check in tool versions and digests (for platforms I use)
lockfile = true 
lockfile_platforms = ["macos-arm64", "linux-x64"]
# disable telemetry
use_versions_host_track = false
# enable experimental features
experimental = true

# cache the computed env
env_cache = true
env_shell_expand = true
# enable automatic venv/tool activation
python.uv_venv_auto = "source"
idiomatic_version_file_enable_tools = ["go", "node", "python", "rust"]

[settings.github]
# re-use gh credentials
credential_command = 'gh auth token -h "${MISE_CREDENTIAL_HOST}"'

use_git_credentials = true

[hooks]
# notify uv of new versions automatically
postinstall = "mise sync python --uv"

# Packages

[tools]
# Languages
go = "latest"
node = "lts"
python = "latest"
rust = { version = "stable", components = "rust-analyzer,rust-src" }

# Installers
aube = "latest"
cargo-binstall = "latest"
uv = "latest"

# General
"go:mvdan.cc/xurls/v2/cmd/xurls" = { version = "latest", depends = ["go"] }
"npm:git-recent" = { version = "latest", depends = ["aube"] }

# Go
"golangci-lint" = "latest"
"go:golang.org/x/tools/cmd/goimports" = { version = "latest", depends = ["go"] }
"go:golang.org/x/vuln/cmd/govulncheck" = { version = "latest", depends = ["go"] }

# Rust
"cargo:cargo-audit" = { version = "latest", depends = ["rust", "cargo-binstall"] }
"cargo:cargo-auditable" = { version = "latest", depends = ["rust", "cargo-binstall"] }
"cargo:cargo-fuzz" = { version = "latest", depends = ["rust", "cargo-binstall"] }
"cargo:cargo-llvm-cov" = { version = "latest", depends = ["rust", "cargo-binstall"] }
"cargo:cargo-outdated" = { version = "latest", depends = ["rust", "cargo-binstall"] }
"cargo:cargo-udeps" = { version = "latest", depends = ["rust", "cargo-binstall"] }
"cargo:flamegraph" = { version = "latest", depends = ["rust", "cargo-binstall"] }
