#!/usr/bin/env bash

set -e

test -f ".pre-commit-config.yaml" || exit 0
command -v pre-commit >/dev/null || exit 0

exec pre-commit hook-impl \
  --config=.pre-commit-config.yaml \
  --hook-type=pre-commit \
  --hook-dir="$(dirname "${BASH_SOURCE[0]}")" \
  -- "$@"

