---
version: '1'
values:
    - type: separator
      display: always
      pre_format: 'printf " %s" \('
      post_format: ''
    - type: remote_difference
      display_if_uptodate: true
      pre_format: ''
      post_format: ''
      values:
        - type: name
          pre_format: '(set_color $color_base00)<LOCAL_BRANCH>'
          post_format: '(set_color normal)'
        - type: ahead
          pre_format: '\>'
          post_format: ''
        - type: behind
          pre_format: '\<'
          post_format: ''
    - type: separator
      display: surrounded
      pre_format: '│'
      post_format: ''
    - type: stash
      pre_format: '(set_color $color_orange)\$'
      post_format: '(set_color normal)'
    - type: conflicts
      pre_format: '(set_color $color_red)\#'
      post_format: '(set_color normal)'
    - type: staged
      pre_format: '(set_color $color_yellow)\+'
      post_format: '(set_color normal)'
    - type: changed
      pre_format: '(set_color $color_blue)\~'
      post_format: '(set_color normal)'
    - type: new
      pre_format: '(set_color $color_base1)\?'
      post_format: '(set_color normal)'
    - type: separator
      display: surrounded
      pre_format: '│'
      post_format: ''
    - type: repository_state
      pre_format: '(set_color $color_red)'
      post_format: '(set_color normal)'
    - type: separator
      display: always
      pre_format: ''
      post_format: '\)'
