#!/usr/bin/env bash

# Load global config.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Load local config.
if [ -f $HOME/.xinitrc.local ]; then
  source $HOME/.xinitrc.local
fi

#
# Environment
#

# Make sure to allow tmux.
unset TMUX

#
# Background
#

# Load the background with feh.
feh --bg-scale ~/.dotfiles/img/bg.jpg &
# Start compton (X compositor).
compton &
# Start devmon (userspace auto-mounter).
devmon &
# Start dunst (notification daemon).
dunst &
# Start PulseAudio (sound server).
start-pulseaudio-x11 &
# Start Redshift (screen tinter).
redshift -l 34.05:-118.25 -t 6500:3500 &
# Start SpaceFM daemon (file manager).
spacefm -d &
# Start unclutter (mouse hiding daemon).
unclutter &
# Start xautolock (screen locker/timer).
xautolock -secure -locker slock -time 5 -corners ---- &
# Start xbindkeys (keyboard mapping daemon).
xbindkeys &
# Load keymap.
xmodmap ~/.Xmodmap &


#
# Session
#

# Default to dwm.
session=${1:-dwm}

# Run dwm status daemon if we're running dwm.
if [ $session == "dwm" ]; then
  dwmstatus &
fi

case $session in
    dwm) exec dwm;;
    i3 ) exec i3;;
    *  ) exec $session;;
esac
