#!/usr/bin/env bash


# Load the global files.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Make sure to allow tmux.
unset TMUX

# Load my custom keybinds.
xmodmap ~/.Xmodmap &

# Set the background.
feh --bg-scale ~/.dotfiles/img/bg.jpg &

# Start the tinting daemon.
redshift -l 34.05:-118.25 -t 6500:3500 &

# Start the locking daemon.
xautolock -locker slock -time 5 -corners 0-00 &

# Start the notification daemon.
dunst &

session=${1:-dwm}
case $session in
    dwm|dwmd) exec dwmd;;
    i3|i3wm ) exec i3;;
    *       ) exec $session;;
esac
