#!/usr/bin/env bash

# Load the global files.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Make sure to allow tmux.
unset TMUX

# Set the background.
feh --bg-scale ~/.dotfiles/img/bg.jpg &

# Load my custom keybinds.
xmodmap ~/.Xmodmap &
# Start the keyboard binding daemon.
xbindkeys &

# Start the notification daemon.
dunst &

# Start the filemanagement daemon.
spacefm -d &

# Start the auto-mount daemon.
devmon &

# Start the tinting daemon.
redshift -l 34.05:-118.25 -t 6500:3500 &

# Start the locking daemon.
xautolock -locker slock -time 5 -corners 0-00 &

if [ -f $HOME/.xinitrc.local ]; then
  source $HOME/.xinitrc.local
fi

# Default to dwm.
session=${1:-dwm}

# Run dwm status daemon if we're running dwm.
if [ $session == "dwm" ]; then
  dwmstatus &
fi

case $session in
    dwm) exec dwm;;
    i3 ) exec i3;;
    *  ) exec $session;;
esac
