#!/bin/sh

set -e

. lib/env.sh
. lib/install.sh
. lib/logging.sh
. lib/registry.sh
. lib/utils.sh

section "System Packages"
case $(uname) in
  Linux)
    if command -v pacman >/dev/null; then
      BLD="autoconf automake bison ccache clang cmake fakeroot gcc make pkgconf"
      LIB="libyaml"
      USR="ctags elinks fish gdb git git-lfs htop jq lftp perl-file-mimeinfo mosh neofetch neovim shellcheck socat stow tig tmux unzip whois xdg-utils"

      INSTALLED=$(pacman -Qq)
    elif command -v apt-get >/dev/null; then
      BLD="automake bison ccache clang cmake gcc g++ make pkgconf"
      LIB="libbz2-dev libffi-dev libgdbm-dev libncurses-dev libreadline-dev libsqlite3-dev libssl-dev liblzma-dev libyaml-dev uuid-dev zlib1g-dev"
      USR="curl elinks exuberant-ctags fish gdb git git-lfs htop jq lftp libarchive-tools libfile-mimeinfo-perl mosh neofetch neovim shellcheck socat stow task-spooler tig tmux unzip whois xdg-utils"

      INSTALLED=$(dpkg-query -f '${Package}\n' -W)
    elif command -v dnf >/dev/null; then
      BLD="automake bison ccache clang cmake compiler-rt gcc make pkgconf"
      LIB="bzip2-devel gdbm-devel libffi-devel libuuid-devel libyaml-devel lzma-devel ncurses-devel openssl-devel readline-devel sqlite-devel zlib-devel"
      USR="ctags elinks fish gdb git git-lfs gnupg htop jq lftp bsdtar perl-File-MimeInfo mosh neofetch neovim ShellCheck socat stow task-spooler tig tmux unzip whois xdg-utils"

      INSTALLED=$(dnf repoquery --installed --queryformat '%{name}')
    else
      error "Unsupported package manager."
    fi
    ;;
  FreeBSD)
    BLD="automake ccache cmake gcc gmake pkgconf"
    LIB="libffi libyaml ncurses openssl readline sqlite3"
    USR="bash coreutils curl elinks fish gdb git git-lfs gnupg hs-ShellCheck htop jq lftp mosh neofetch neovim p5-File-MimeInfo pinentry-curses postgresql10-client python python2 python3 socat stow tig tmux ts universal-ctags unzip whois xdg-utils"
    INSTALLED=$(pkg query '%n')
    ;;
  Darwin)
    BLD="automake ccache cmake"
    LIB="gmp gdbm libffi libyaml openssl readline"
    USR="coreutils ctags curl fish gdb git git-lfs gnupg htop jq lftp mosh neofetch neovim pinentry-mac shellcheck socat stow task-spooler tmux unzip xz"

    INSTALLED=$(brew ls -1)
    ;;
  *)
    error "Unsupported operating system."
    ;;
esac
for pkg in $BLD $LIB $USR; do
  if ! echo "$INSTALLED" | grep -Fwq "$pkg"; then
    PKGS="${PKGS:+$PKGS }$pkg"
  fi
done
if [ -n "$PKGS" ]; then
  if [ -z "$SKIP_PKGS" ]; then
    case $(uname) in
      Linux)
        if command -v pacman >/dev/null; then
          info "Installing system packages with pacman..."
          sudo sh -c "pacman -Sy --noconfirm $PKGS"
        elif command -v apt-get >/dev/null; then
          info "Installing system packages with apt..."
          sudo sh -c "apt-get install --no-install-recommends -y $PKGS"
        elif command -v dnf >/dev/null; then
          info "Installing system packages with dnf..."
          sudo sh -c "dnf install --setopt=install_weak_deps=False --best -y $PKGS"
        fi
        ;;
      FreeBSD)
        info "Installing system packages with pkg..."
        su root -c "pkg install -y $PKGS"
        ;;
      Darwin)
        info "Installing system packages with brew..."
        sh -c "brew install $PKGS"
        ;;
    esac
  else
    important "The following system packages are missing:"
    echo "$PKGS"
  fi
else
  info "All system packages are installed."
fi

section "Language Support"
for support in support/*.sh; do
  if ! echo "$SKIP_LANGUAGES" | grep -Fq "$(stem "$support")"; then
    # shellcheck source=/dev/null
    . "$support"
  fi
done

section "Toolsets"
for toolset in toolset/*.sh; do
  if ! echo "$SKIP_TOOLSETS" | grep -Fq "$(stem "$toolset")"; then
    # shellcheck source=/dev/null
    . "$toolset"
  fi
done

important "Done! Restart your shell!"
