#!/bin/sh

set -e

. lib/env.sh
. lib/install.sh
. lib/logging.sh
. lib/registry.sh
. lib/utils.sh

section "System Packages"
case $(uname) in
  Linux)
    BLD="automake bison ccache clang cmake gcc g++ make pkgconf"
    LIB="libbz2-dev libffi-dev libgdbm-dev libncurses-dev libreadline-dev libsqlite3-dev libssl-dev liblzma-dev libyaml-dev uuid-dev zlib1g-dev"
    USR="bzip2 cmatrix curl elinks fish gdb git git-lfs gnupg htop jq lftp libarchive-tools libfile-mimeinfo-perl mosh neofetch neovim shellcheck socat stow tig tmux unzip vlock whois xdg-utils xz-utils"

    INSTALLED=$(dpkg-query -f '${Package}\n' -W)
    ;;
  FreeBSD)
    BLD="automake ccache cmake gcc gmake pkgconf"
    LIB="libffi libyaml ncurses openssl readline sqlite3"
    USR="bash cmatrix coreutils curl elinks fish gdb git git-lfs gnupg htop jq lftp mosh neofetch neovim p5-File-MimeInfo pinentry-curses python python2 python3 hs-ShellCheck socat tig tmux stow universal-ctags unzip vlock whois xdg-utils"

    INSTALLED=$(pkg query '%n')
    ;;
  Darwin)
    BLD="automake ccache cmake"
    LIB="gmp gdbm libffi libyaml openssl readline"
    USR="cmatrix coreutils ctags curl fish gdb git git-lfs gnupg htop jq lftp mosh neofetch neovim pinentry-mac shellcheck socat stow tmux unzip xz"

    INSTALLED=$(brew ls -1)
    ;;
  *)
    error "Unsupported operating system."
    ;;
esac
for pkg in $BLD $LIB $USR; do
  if ! echo "$INSTALLED" | grep -Fwq "$pkg"; then
    PKGS="${PKGS:+$PKGS }$pkg"
  fi
done
if [ -n "$PKGS" ]; then
  if [ -z "$SKIP_PKGS" ]; then
    case $(uname) in
      Linux)
        info "Installing system packages with apt..."
        sudo sh -c "apt-get install --no-install-recommends -y $PKGS"
        ;;
      FreeBSD)
        info "Installing system packages with pkg..."
        su root -c "pkg install -y $PKGS"
        ;;
      Darwin)
        info "Installing system packages with brew..."
        sh -c "brew install $PKGS"
        ;;
    esac
  else
    important "The following system packages are missing:"
    echo "$PKGS"
  fi
else
  info "All system packages are installed."
fi

section "Language Support"
for support in support/*.sh; do
  if ! echo "$SKIP_LANGUAGES" | grep -Fq "$(stem "$support")"; then
    # shellcheck source=/dev/null
    . "./$support"
  fi
done

section "Toolsets"
for toolset in toolset/*.sh; do
  if ! echo "$SKIP_TOOLSETS" | grep -Fq "$(stem "$toolset")"; then
    # shellcheck source=/dev/null
    . "./$toolset"
  fi
done

important "Done! Restart your shell!"
