#!/usr/bin/env python

import glob
import os
import sys
import time

if len(sys.argv) != 5:
    msg = 'usage: %s <prefix> <keep> <source_dir> <snapshot_dir>\n' \
           % os.path.basename(sys.argv[0])
    msg += '\n'
    msg += '   prefix: backup name prefix, for example "1h" or "5m".\n'
    msg += '   keep: Number of copies of this to keep.\n'
    msg += '   source_dir: btrfs file-system mount-point to snapshot.\n'
    msg += '   snapshot_dir: Directory to put snapshots in.\n'
    sys.stderr.write(msg)
    sys.exit(1)

btrfs = '/usr/bin/btrfs'
dateformat = '%Y%m%d-%H%M%S'

prefix = sys.argv[1]
keep = int(sys.argv[2])
source_dir = sys.argv[3]
snapshot_dir = sys.argv[4]

if not os.path.exists(snapshot_dir):
    sys.stderr.write('error: snapshot_dir does not exist!\n')
    sys.exit(1)

snap = '%s-%s' % (prefix, time.strftime(dateformat))
os.system('%s subvolume snapshot "%s" "%s/%s" >/dev/null 2>&1'
          % (btrfs, source_dir, snapshot_dir, snap))

oldcopies = sorted(glob.glob(os.path.join(snapshot_dir, '%s-*' % prefix)))
for oldsnap in oldcopies[:0-keep]:
    os.system('%s subvolume delete "%s" >/dev/null 2>&1' % (btrfs, oldsnap))
