#!/usr/bin/env bash

set -e
set -o pipefail
set -u

if [[ !($# -eq 2) ]]; then 
	echo "usage: $0 <FLAC> <MP3>"
	exit 1
fi

FLAC=$1
MP3=$2

echo "$FLAC -> $MP3"

for tag in TITLE ARTIST ALBUM DATE COMMENT TRACKNUMBER TRACKTOTAL GENRE; do
  eval "$tag=\"$(metaflac --show-tag=$tag "$FLAC" | sed 's/.*=//')\""
done

flac -cd "$FLAC" | lame -V0 --add-id3v2 --tt "$TITLE" --ta "$ARTIST" --tl "$ALBUM" --ty "$DATE" --tc "$COMMENT" --tn "$TRACKNUMBER/$TRACKTOTAL" --tg "$GENRE" - "$MP3"
