#!/usr/bin/env bash

FZF_URL_REGEX='(?i)(https?|ftp)://[^\s/$.?#].[^\s]*$'

if [ -n "$*" ]; then
  exec sh -c "cat $* | $0"
fi

tmux unbind -na
grep -oP "$FZF_URL_REGEX" | fzf-tmux -m --tac | while read -r url; do
  message=$(sh -c "$BROWSER $url") || tmux display-message "$message"
done
tmux source ~/.tmux.conf
