#!/usr/bin/env bash

mkdir -p ~/.ndenv
cd ~/.ndenv

git init
git remote add origin git://github.com/riywo/ndenv
git fetch
git checkout -t origin/master

mkdir ~/.ndenv/plugins
cd ~/.ndenv/plugins

git clone git://github.com/riywo/node-build
