#!/bin/sh

PYENV_ROOT="$HOME/.pyenv"

git clone https://github.com/yyuu/pyenv $PYENV_ROOT
git clone https://github.com/pyenv/pyenv-ccache $PYENV_ROOT/plugins/pyenv-ccache
git clone https://github.com/pyenv/pyenv-doctor $PYENV_ROOT/plugins/pyenv-doctor
git clone https://github.com/pyenv/pyenv-installer $PYENV_ROOT/plugins/pyenv-installer
git clone https://github.com/pyenv/pyenv-pip-migrate $PYENV_ROOT/plugins/pyenv-pip-migrate
git clone https://github.com/pyenv/pyenv-pip-rehash $PYENV_ROOT/plugins/pyenv-pip-rehash
git clone https://github.com/massongit/pyenv-pip-update $PYENV_ROOT/plugins/pyenv-pip-update
git clone https://github.com/pyenv/pyenv-update $PYENV_ROOT/plugins/pyenv-update
git clone https://github.com/pyenv/pyenv-virtualenv $PYENV_ROOT/plugins/pyenv-virtualenv
