#!/usr/bin/env bash

mkdir -p ~/.pyenv
cd ~/.pyenv

git init
git remote add origin git://github.com/yyuu/pyenv
git fetch
git checkout -t origin/master

mkdir ~/.pyenv/plugins
cd ~/.pyenv/plugins

git clone git://github.com/yyuu/pyenv-doctor
git clone git://github.com/yyuu/pyenv-version-ext
git clone git://github.com/yyuu/pyenv-pip-migrate
git clone git://github.com/yyuu/pyenv-pip-rehash
git clone git://github.com/yyuu/pyenv-update
