#!/usr/bin/env bash

WIDTH=120
HEIGHT=36

cmd=$1
# Default to $SHELL.
if [[ -z $cmd ]]; then
  cmd=$SHELL
fi

class=quickterm-$cmd

quickterm_id () {
  id=$(xdo id -N "$class")
  status=$?

  if [[ $TERMINAL =~ "termite" ]]; then
    badids=$(xdo id -a "termite")
    id=$(echo "$id" | grep -v "$badids")
  fi

  echo "$id"
  return $status
}

# Check if quickterm already is running.
if id=$(quickterm_id); then
  if [[ $id == $(xdo id) ]]; then
    # A quickterm is running and active, hide it.
    xdo hide "$id"
  else
    # A quickterm is running and hidden, show it.
    xdo show "$id"
    xdo activate "$id"
  fi
else
  # No quickterm is running, run one.
  if [[ $TERMINAL =~ "alacritty" ]]; then
    "$TERMINAL" -t "$class" -d $WIDTH $HEIGHT -e "$cmd" &
  elif [[ $TERMINAL =~ "termite" ]]; then
    WIDTH=$((WIDTH*8))
    HEIGHT=$((HEIGHT*18))
    "$TERMINAL" --class="$class" --geometry=${WIDTH}x${HEIGHT} -e "$cmd" &
  else
    "$TERMINAL" -class "$class" -geometry ${WIDTH}x${HEIGHT} -e "$cmd" &
  fi
fi

# Block until the terminal is ready.
while ! id=$(quickterm_id); do
  sleep 0.2
done

# Center the window.
if [[ $DESKTOP_SESSION =~ i3 ]]; then
  i3-msg "[id=$id] move position center"
fi

(
  # Loop until quickterm exits or we lose focus.
  while id=$(quickterm_id); do
    if [[ $id != $(xdo id) ]]; then
      # Hide quickterm on focus lost, then exit.
      xdo hide "$id"
      exit
    fi
  done
) &
