#!/bin/sh

RBENV_ROOT="$HOME/.rbenv"

git clone https://github.com/rbenv/rbenv $RBENV_ROOT
git clone https://github.com/rbenv/ruby-build $RBENV_ROOT/plugins/ruby-build
git clone https://github.com/tpope/rbenv-aliases $RBENV_ROOT/plugins/rbenv-aliases
git clone https://github.com/ianheggie/rbenv-binstubs $RBENV_ROOT/plugins/rbenv-binstubs
git clone https://github.com/yyuu/rbenv-ccache $RBENV_ROOT/plugins/rbenv-ccache
git clone https://github.com/tpope/rbenv-communal-gems $RBENV_ROOT/plugins/rbenv-communal-gems
git clone https://github.com/tpope/rbenv-ctags $RBENV_ROOT/plugins/rbenv-ctags
git clone https://github.com/rbenv/rbenv-each $RBENV_ROOT/plugins/rbenv-each
git clone https://github.com/rbenv/rbenv-installer $RBENV_ROOT/plugins/rbenv-installer
git clone https://github.com/rkh/rbenv-update $RBENV_ROOT/plugins/rbenv-update
git clone https://github.com/mislav/rbenv-user-gems $RBENV_ROOT/plugins/rbenv-user-gems
