#!/usr/bin/env bash

mkdir -p ~/.rbenv
cd ~/.rbenv

git init
git remote add origin git://github.com/sstephenson/rbenv
git fetch
git checkout -t origin/master

mkdir ~/.rbenv/plugins
cd ~/.rbenv/plugins

git clone git://github.com/sstephenson/ruby-build

git clone git://github.com/tpope/rbenv-aliases
git clone git://github.com/ianheggie/rbenv-binstubs
git clone git://github.com/yyuu/rbenv-ccache
git clone git://github.com/tpope/rbenv-communal-gems
git clone git://github.com/tpope/rbenv-ctags
git clone git://github.com/sstephenson/rbenv-default-gems
git clone git://github.com/chriseppstein/rbenv-each
git clone git://github.com/ianheggie/rbenv-env
git clone git://github.com/sstephenson/rbenv-gem-rehash
git clone git://github.com/mlafeldt/rbenv-man
git clone git://github.com/tpope/rbenv-sentience
git clone git://github.com/dcarley/rbenv-sudo
git clone git://github.com/rkh/rbenv-update
git clone git://github.com/rkh/rbenv-use
git clone git://github.com/mislav/rbenv-user-gems
git clone git://github.com/sstephenson/rbenv-vars
git clone git://github.com/rkh/rbenv-whatis
