#!/usr/bin/env bash

URL_REGEX="https?://[^[:space:]]+"

pane="$1"
op="$2"
type="$3"

[ -n "$pane" ] || exit 1
[ -n "$op" ] || op="open"

if [ "$type" = "full" ]; then
  data=$(tmux capture-pane -Jp -S- -E- -t "$pane")
else
  data=$(tmux capture-pane -Jp -t "$pane")
fi

(grep -iIohE "$URL_REGEX" | fzf -m --tac) <<< """$data""" | while read -r url; do
  if [ "$op" = "open" ]; then
    $BROWSER "$url"
  elif [ "$op" = "copy" ]; then
    case $(uname) in
      Darwin) echo "$url" | pbcopy;;
      Linux) echo "$url" | xsel -b -i;;
    esac
  fi
done

