#!/usr/bin/env ruby

require 'tempfile'

VIM = 'nvim'

config = ENV['XDG_CONFIG_HOME'] || File.join(ENV['HOME'], '.config')
vimfiles = File.join(config, VIM, 'pack', 'minpac', 'start')
log = Tempfile.new('vimprofile')

puts "Profiling plugin startup performance (from #{vimfiles})..."
system(VIM, '--startuptime', log.path, '-c', 'q')

times = Hash.new(0)
lines = log.readlines.select { |line| line =~ /sourcing.*#{Regexp.escape(vimfiles)}/ }
lines.each do |line|
  trace_time, source_time, exec_time, _, path = line.split(' ')

  relative_path = path.gsub(vimfiles + '/', '')
  name = File.basename(relative_path.split('/')[0], '.vim')

  times[name] += exec_time.to_f
end

maximum   = times.values.max
total     = times.values.inject(:+)
justify   = times.keys.map(&:length).max
relatives = Hash[ times.map { |k, v| [k, v/maximum] } ]

relatives.sort_by { |k, v| -v }.each do |k, v|
  name  = k.rjust(justify)
  time  = times[k].round(3).to_s.ljust(5) + "ms"
  graph = '*' * (v * 150)

  puts "#{name}: (#{time}) #{graph}"
end
puts "#{"total".rjust(justify)}: #{total.round(3).to_s}ms"

log.unlink
