#!/usr/bin/env bash

format=""
player="mpv --quiet --geometry=50%:50% --keep-open"

url="$1"
filepath="${TMP:-/tmp}/$(youtube-dl --id --get-filename $format $url)"

youtube-dl -c -o $filepath $format $url &
echo $! > $filepath.$$.pid

while [ ! -r $filepath ] && [ ! -r $filepath.part ]; do sleep 1; done

[ -r $filepath.part ] && $player $filepath.part  || $player $filepath

kill $(cat $filepath.$$.pid); rm $filepath.$$.pid
