#!/bin/sh

# Default to i3.
export DESKTOP_SESSION=${1:-i3}
# Assume X11 by default.
export XDG_SESSION_TYPE=${XDG_SESSION_TYPE:-x11}

# Load profile.
for f in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile" "$HOME/.xprofile.local"; do
  test -f "$f" && source "$f"
done

# Load resources.
for f in "/etc/X11/Xresources" "$HOME/.Xresources"; do
  test -f "$f" && xrdb -merge "$f"
done

# Load keymaps.
for f in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
  test -f "$f" && setxkbmap < "$f"
done
for f in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
  test -f "$f" && xmodmap "$f"
done

# Load global config.
if test -d /etc/X11/xinit/xinitrc.d; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  test -x "$f" && source "$f"
 done
fi

# Load user config.
for f in "$HOME/.xsession" "$HOME/.xsession.local"; do
  test -f "$f" && source "$f"
done

case $DESKTOP_SESSION in
  i3 ) exec i3;;
  *  ) exec "$DESKTOP_SESSION";;
esac
