#!/usr/bin/env bash

# Notify systemd of startup.
systemctl --user start $XDG_SESSION_TYPE.target

# Notify gpg-agent of a graphical session.
unset GPG_TTY
gpg-connect-agent updatestartuptty /bye

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
  # Set display timeout.
  xset s 300 300
  xset dpms 300 300 300

  if [[ "$DESKTOP_SESSION" =~ "dwm" ]]; then
    pkill -f dwmstatus >/dev/null; dwmstatus &
  fi
  pkill -f lxpolkit >/dev/null; lxpolkit &
  pkill -f xss-lock >/dev/null; xss-lock -- xlock &

  test -f ~/.fehbg && sh ~/.fehbg
fi
