#!/bin/sh

# Default to i3.
export DESKTOP_SESSION=${1:-i3}

# Load resources.
for f in "/etc/X11/Xresources" "/usr/local/etc/X11/.Xresources" "$HOME/.Xresources"; do
  test -f "$f" && xrdb -merge "$f"
done

# Load keymaps.
for f in "/etc/X11/Xmodmap" "/usr/local/etc/X11/.Xmodmap" "$HOME/.Xmodmap"; do
  test -f "$f" && xmodmap "$f"
done
for f in "/etc/X11/Xkbmap" "/usr/local/etc/X11/.Xkbmap" "$HOME/.Xkbmap"; do
  test -f "$f" && setxkbmap < "$f"
done

# Load global config.
for d in "/etc/X11/xinit/xinitrc.d" "/usr/local/etc/X11/xinitrc.d"; do
  if test -d "$d"; then
    for f in "$d"/*.sh; do
      test -x "$f" && . "$f"
    done
  fi
done

case $DESKTOP_SESSION in
  i3 ) exec i3;;
  *  ) exec "$DESKTOP_SESSION";;
esac
