#!/bin/sh

if command -v systemctl >/dev/null; then
  # Import the environment into systemd.
  systemctl --user import-environment
  # Notify systemd of startup.
  systemctl --user start "$XDG_SESSION_TYPE.target"
fi

# Notify gpg-agent of a graphical session.
if command -v gpg-connect-agent >/dev/null; then
  unset GPG_TTY
  gpg-connect-agent updatestartuptty /bye
fi

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
  # Set display timeout.
  xset s 300 300
  xset dpms 300 300 300

  pkill -f lxpolkit >/dev/null; lxpolkit &
  pkill -f xss-lock >/dev/null; xss-lock -- lockx &

  test -f ~/.fehbg && sh ~/.fehbg
fi
